routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::group(['middleware' => ['web','auth']], function () {
    Route::get('/', function () {
        return view('admin.dashboard');
    });

    /*Organization Routes*/
    Route::get('organization/profile','Admin\OrganizationProfileController@profile')->name('organization.profile');
    Route::post('organization/profile/update','Admin\OrganizationProfileController@UpdateProfile')->name('organization.profile.update');
    /*End Organization Routes*/

    Route::resource('donors', 'Admin\DonorController');
    Route::resource('ethnicities', 'Admin\EthnicityController');
    Route::resource('mne-categories', 'Admin\MNECategoryController');
    Route::resource('budget-categories', 'Admin\BudgetCategoryController');
    Route::resource('partners', 'Admin\PartnerController');
    Route::resource('projects', 'Admin\ProjectController');
});


Route::prefix('project')->middleware('auth')->group(function(){

    Route::get('/{id}/dashboard','ProjectSetup\ProjectController@index');
    
    Route::resource('/{id}/mneactivities','ProjectSetup\MNEActivityController');
    Route::resource('/{id}/geographicregions','ProjectSetup\GeographicController');
    Route::resource('/{id}/beneficiaries','ProjectSetup\BeneficiariesController');
    Route::resource('/{id}/quarters','ProjectSetup\QuarterController');

    Route::resource('/{project_id}/indicators','ProjectSetup\ProjectIndicatorController',['as'=>'projects']);    
    Route::resource('/{project_id}/{type}/{id}/indicators','ProjectSetup\IndicatorController');

    Route::resource('/{project_id}/activities/{activity_id}/activity-planner','ProjectSetup\ActivityPlannerController',['as' => 'activities', 'except' => ['show']]);
    Route::get('/{project_id}/activities/activity-planner','ProjectSetup\ActivityPlannerController@all')->name('activities.activity-planner');

    Route::get('/{project_id}/activities/budget-planner','ProjectSetup\ActivityBudgetController@index')->name('finance.activity-budget-planner.index');
    Route::get('/{project_id}/activities/{activity_id}/budget-planner','ProjectSetup\ActivityBudgetController@show')->name('finance.activity-budget-planner');
    Route::post('/{project_id}/activities/{activity_id}/budget-planner','ProjectSetup\ActivityBudgetController@update');

    Route::get('/{project_id}/mne/budget-planner','ProjectSetup\MNEBudgetController@index')->name('finance.mne-budget-planner.index');
    Route::get('/{project_id}/mne/{mne_id}/budget-planner','ProjectSetup\MNEBudgetController@show')->name('finance.mne-budget-planner');
    Route::post('/{project_id}/mne/{mne_id}/budget-planner','ProjectSetup\MNEBudgetController@update');

    Route::resource('/{project_id}/narrative-records','ProjectSetup\NarrativeRecordController',[ 'as' => 'finance','except' => ['create','show'] ]);
    Route::resource('/{project_id}/budget-docs','ProjectSetup\BudgetDocController',[ 'as' => 'finance','except' => ['create'] ]);

    Route::resource('/{project_id}/docs','ProjectSetup\ProjectDocumentController');

    Route::resource('/{project_id}/questions-planner','ProjectSetup\QuestionController',['as' => 'settings','except' => ['create','show']]);

    Route::group(['namespace' => 'ProjectOperation',], function(){
        Route::get('/{project_id}/indicator-evaluation','ProjectEntryController@getEvaluation')->name('projects.indicator-evaluation.get');
        Route::post('/{project_id}/indicator-evaluation/save','ProjectEntryController@saveEvaluation')->name('projects.indicator-evaluation.save');

        Route::get('/{project_id}/progress-report','ProjectEntryController@getReport')->name('projects.progress-report.get');
        Route::post('/{project_id}/progress-report/save','ProjectEntryController@saveReport')->name('projects.progress-report.save');

        Route::get('/{project_id}/outcomes/indicator-evaluation','OutcomeEntryController@indexEvaluation')->name('outcomes.indicator-evaluation.index');
        Route::get('/{project_id}/outcomes/{outcome_id}/indicator-evaluation','OutcomeEntryController@getEvaluation')->name('outcomes.indicator-evaluation.get');
        Route::post('/{project_id}/outcomes/{outcome_id}/indicator-evaluation/save','OutcomeEntryController@saveEvaluation')->name('outcomes.indicator-evaluation.save');

        Route::get('/{project_id}/outcomes/progress-report','OutcomeEntryController@indexReport')->name('outcomes.progress-report.index');
        Route::get('/{project_id}/outcomes/{outcome_id}/progress-report','OutcomeEntryController@getReport')->name('outcomes.progress-report.get');
        Route::post('/{project_id}/outcomes/{outcome_id}/progress-report/save','OutcomeEntryController@saveReport')->name('outcomes.progress-report.save');

        Route::get('/{project_id}/outputs/indicator-evaluation','OutputEntryController@indexEvaluation')->name('outputs.indicator-evaluation.index');
        Route::get('/{project_id}/outputs/{output_id}/indicator-evaluation','OutputEntryController@getEvaluation')->name('outputs.indicator-evaluation.get');
        Route::post('/{project_id}/outputs/{output_id}/indicator-evaluation/save','OutputEntryController@saveEvaluation')->name('outputs.indicator-evaluation.save');

        Route::get('/{project_id}/outputs/progress-report','OutputEntryController@indexReport')->name('outputs.progress-report.index');
        Route::get('/{project_id}/outputs/{output_id}/progress-report','OutputEntryController@getReport')->name('outputs.progress-report.get');
        Route::post('/{project_id}/outputs/{output_id}/progress-report/save','OutputEntryController@saveReport')->name('outputs.progress-report.save');

        Route::get('/{project_id}/activities/indicator-evaluation','ActivityEntryController@indexEvaluation')->name('activities.indicator-evaluation.index');
        Route::get('/{project_id}/activities/{activity_id}/indicator-evaluation','ActivityEntryController@getEvaluation')->name('activities.indicator-evaluation.get');
        Route::post('/{project_id}/activities/{activity_id}/indicator-evaluation/save','ActivityEntryController@saveEvaluation')->name('activities.indicator-evaluation.save');

    });

    Route::resource('/{id}/outcomes','ProjectSetup\OutcomeController');
    Route::resource('/{id}/outputs','ProjectSetup\OutputController');
    Route::resource('/{id}/activities','ProjectSetup\ActivityController');

});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/partials/footer.blade.php
</div>
</div>
</div>
<footer class="footer">
    <div class="container-fluid">
      <nav class="float-left">
        <ul>
          <li>
            <a href="https://www.creative-tim.com">
              Creative Tim
            </a>
          </li>
          <li>
            <a href="https://creative-tim.com/presentation">
              About Us
            </a>
          </li>
          <li>
            <a href="http://blog.creative-tim.com">
              Blog
            </a>
          </li>
          <li>
            <a href="https://www.creative-tim.com/license">
              Licenses
            </a>
          </li>
        </ul>
      </nav>
      <div class="copyright float-right">
        &copy;
        <script>
          document.write(new Date().getFullYear())
        </script>, made with <i class="material-icons">favorite</i> by
        <a href="https://www.creative-tim.com" target="_blank">Creative Tim</a> for a better web.
      </div>
    </div>
  </footer>
</div>
</div>

<!--   Core JS Files   -->
<script src="/assets/js/core/jquery.min.js"></script>
<script src="/assets/js/core/popper.min.js"></script>
<script src="/assets/js/core/bootstrap-material-design.min.js"></script>
<script src="/assets/js/plugins/perfect-scrollbar.jquery.min.js"></script>
<!-- Plugin for the momentJs  -->
<script src="/assets/js/plugins/moment.min.js"></script>
<!--  Plugin for Sweet Alert -->
<script src="/assets/js/plugins/sweetalert2.js"></script>
<!-- Forms Validations Plugin -->
<script src="/assets/js/plugins/jquery.validate.min.js"></script>
<!-- Plugin for the Wizard, full documentation here: https://github.com/VinceG/twitter-bootstrap-wizard -->
<script src="/assets/js/plugins/jquery.bootstrap-wizard.js"></script>
<!--	Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select -->
<script src="/assets/js/plugins/bootstrap-selectpicker.js"></script>
<!--  Plugin for the DateTimePicker, full documentation here: https://eonasdan.github.io/bootstrap-datetimepicker/ -->
<script src="/assets/js/plugins/bootstrap-datetimepicker.min.js"></script>
<!--  DataTables.net Plugin, full documentation here: https://datatables.net/  -->
<script src="/assets/js/plugins/jquery.dataTables.min.js"></script>
<!--	Plugin for Tags, full documentation here: https://github.com/bootstrap-tagsinput/bootstrap-tagsinputs  -->
<script src="/assets/js/plugins/bootstrap-tagsinput.js"></script>
<!-- Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
<script src="/assets/js/plugins/jasny-bootstrap.min.js"></script>
<!--  Full Calendar Plugin, full documentation here: https://github.com/fullcalendar/fullcalendar    -->
<script src="/assets/js/plugins/fullcalendar.min.js"></script>
<!-- Vector Map plugin, full documentation here: http://jvectormap.com/documentation/ -->
<script src="/assets/js/plugins/jquery-jvectormap.js"></script>
<!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
<script src="/assets/js/plugins/nouislider.min.js"></script>
<!-- Include a polyfill for ES6 Promises (optional) for IE11, UC Browser and Android browser support SweetAlert -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.js"></script>
<!-- Library for adding dinamically elements -->
<script src="/assets/js/plugins/arrive.min.js"></script>
<!--  Google Maps Plugin    -->
<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
<!-- Chartist JS -->
<script src="/assets/js/plugins/chartist.min.js"></script>
<!--  Notifications Plugin    -->
<script src="/assets/js/plugins/bootstrap-notify.js"></script>
<!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
<script src="/assets/js/material-dashboard.js?v=2.1.0" type="text/javascript"></script>
<!-- Material Dashboard DEMO methods, don't include it in your project! -->
<script src="/assets/demo/demo.js"></script>


<script>
$(document).ready(function() {
  $().ready(function() {
    $sidebar = $('.sidebar');

    $sidebar_img_container = $sidebar.find('.sidebar-background');

    $full_page = $('.full-page');

    $sidebar_responsive = $('body > .navbar-collapse');

    window_width = $(window).width();

    fixed_plugin_open = $('.sidebar .sidebar-wrapper .nav li.active a p').html();

    if (window_width > 767 && fixed_plugin_open == 'Dashboard') {
      if ($('.fixed-plugin .dropdown').hasClass('show-dropdown')) {
        $('.fixed-plugin .dropdown').addClass('open');
      }

    }

    $('.fixed-plugin a').click(function(event) {
      // Alex if we click on switch, stop propagation of the event, so the dropdown will not be hide, otherwise we set the  section active
      if ($(this).hasClass('switch-trigger')) {
        if (event.stopPropagation) {
          event.stopPropagation();
        } else if (window.event) {
          window.event.cancelBubble = true;
        }
      }
    });

    $('.fixed-plugin .active-color span').click(function() {
      $full_page_background = $('.full-page-background');

      $(this).siblings().removeClass('active');
      $(this).addClass('active');

      var new_color = $(this).data('color');

      if ($sidebar.length != 0) {
        $sidebar.attr('data-color', new_color);
      }

      if ($full_page.length != 0) {
        $full_page.attr('filter-color', new_color);
      }

      if ($sidebar_responsive.length != 0) {
        $sidebar_responsive.attr('data-color', new_color);
      }
    });

    $('.fixed-plugin .background-color .badge').click(function() {
      $(this).siblings().removeClass('active');
      $(this).addClass('active');

      var new_color = $(this).data('background-color');

      if ($sidebar.length != 0) {
        $sidebar.attr('data-background-color', new_color);
      }
    });

    $('.fixed-plugin .img-holder').click(function() {
      $full_page_background = $('.full-page-background');

      $(this).parent('li').siblings().removeClass('active');
      $(this).parent('li').addClass('active');


      var new_image = $(this).find("img").attr('src');

      if ($sidebar_img_container.length != 0 && $('.switch-sidebar-image input:checked').length != 0) {
        $sidebar_img_container.fadeOut('fast', function() {
          $sidebar_img_container.css('background-image', 'url("' + new_image + '")');
          $sidebar_img_container.fadeIn('fast');
        });
      }

      if ($full_page_background.length != 0 && $('.switch-sidebar-image input:checked').length != 0) {
        var new_image_full_page = $('.fixed-plugin li.active .img-holder').find('img').data('src');

        $full_page_background.fadeOut('fast', function() {
          $full_page_background.css('background-image', 'url("' + new_image_full_page + '")');
          $full_page_background.fadeIn('fast');
        });
      }

      if ($('.switch-sidebar-image input:checked').length == 0) {
        var new_image = $('.fixed-plugin li.active .img-holder').find("img").attr('src');
        var new_image_full_page = $('.fixed-plugin li.active .img-holder').find('img').data('src');

        $sidebar_img_container.css('background-image', 'url("' + new_image + '")');
        $full_page_background.css('background-image', 'url("' + new_image_full_page + '")');
      }

      if ($sidebar_responsive.length != 0) {
        $sidebar_responsive.css('background-image', 'url("' + new_image + '")');
      }
    });

    $('.switch-sidebar-image input').change(function() {
      $full_page_background = $('.full-page-background');

      $input = $(this);

      if ($input.is(':checked')) {
        if ($sidebar_img_container.length != 0) {
          $sidebar_img_container.fadeIn('fast');
          $sidebar.attr('data-image', '#');
        }

        if ($full_page_background.length != 0) {
          $full_page_background.fadeIn('fast');
          $full_page.attr('data-image', '#');
        }

        background_image = true;
      } else {
        if ($sidebar_img_container.length != 0) {
          $sidebar.removeAttr('data-image');
          $sidebar_img_container.fadeOut('fast');
        }

        if ($full_page_background.length != 0) {
          $full_page.removeAttr('data-image', '#');
          $full_page_background.fadeOut('fast');
        }

        background_image = false;
      }
    });

    $('.switch-sidebar-mini input').change(function() {
      $body = $('body');

      $input = $(this);

      if (md.misc.sidebar_mini_active == true) {
        $('body').removeClass('sidebar-mini');
        md.misc.sidebar_mini_active = false;

        $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar();

      } else {

        $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar('destroy');

        setTimeout(function() {
          $('body').addClass('sidebar-mini');

          md.misc.sidebar_mini_active = true;
        }, 300);
      }

      // we simulate the window Resize so the charts will get updated in realtime.
      var simulateWindowResize = setInterval(function() {
        window.dispatchEvent(new Event('resize'));
      }, 180);

      // we stop the simulation of Window Resize after the animations are completed
      setTimeout(function() {
        clearInterval(simulateWindowResize);
      }, 1000);

    });
  });
});
</script>
<script>
  $('.delete').click(function () {
    var panel = $(this).attr("panel");
    var id = $(this).attr("cid");
    swal({
      title: 'Are you sure?',
      text: "You won't be able to revert this!",
      type: 'warning',
      showCancelButton: true,
      confirmButtonClass: 'btn btn-success',
      cancelButtonClass: 'btn btn-danger',
      confirmButtonText: 'Yes, delete it!',
      buttonsStyling: false
    }).then((result) => {
      if (result.value) {
        $.ajaxSetup({
          headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
          }
        });
        $.ajax(
                {
                  url: $(this).attr('data-action'),
                  type: 'delete',
                  data: {
                    "id": id,
                    "_token": "{{ csrf_token() }}",
                  },
                  success: function ()
                  {
                    swal({
                      title: 'Deleted!',
                      text: panel+ ' deleted successfully.',
                      type: 'success',
                      confirmButtonClass: "btn btn-success",
                      buttonsStyling: false
                    }).then(function () {
                      location.reload();
                    });
                  },
                  error: function(xhr) {
                    console.log(xhr.responseText);
                  }
                });

      }
    }).then(function(){

    }).catch(swal.noop)
  });

</script>
<script>
  $('.delete-view').click(function () {
    swal({
      title: 'Are you sure?',
      text: "You won't be able to revert this!",
      type: 'warning',
      showCancelButton: true,
      confirmButtonClass: 'btn btn-success',
      cancelButtonClass: 'btn btn-danger',
      confirmButtonText: 'Yes, delete it!',
      buttonsStyling: false
    }).then((result) => {
      if (result.value) {
        $('#delete_from_view').submit();
      }
    }).then(function(){

    }).catch(swal.noop)
  });
</script>
@yield('js')
</body>

</html>

resources/views/admin/partials/header.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="/assets/img/apple-icon.png">
  <link rel="icon" type="image/png" href="/assets/img/favicon.png">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    Restless Development
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  <!-- CSS Files -->
  <link href="/assets/css/material-dashboard.css?v=2.1.0" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link href="/assets/demo/demo.css" rel="stylesheet" />
  @yield('css')
</head>

resources/views/admin/partials/navbar.blade.php
<body class="">
    <div class="wrapper ">
      <div class="sidebar" data-color="rose" data-background-color="black" data-image="../assets/img/sidebar-1.jpg">
        <!--
          Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"
  
          Tip 2: you can also add an image using data-image tag
      -->
        <div class="sidebar-wrapper">
          <div class="user">
            <div class="photo">
              @if($organization_profile_info->logo != null)
                <img src="{{asset('images/organization_images'.'/'.$organization_profile_info->logo)}}" />
                @else
                <span class="sidebar-mini"> {{$organization_profile_info->shortname}} </span>
                @endif
            </div>
            <div class="user-info">
              <a data-toggle="collapse" href="#collapseExample" class="username">
                <span>
                  {{$organization_profile_info->fullname ? $organization_profile_info->fullname : 'Rainbow'}}
                  <b class="caret"></b>
                </span>
              </a>
              <div class="collapse {{\Request::is('organization/profile*') ? 'show' :''}}" id="collapseExample">
                <ul class="nav">
                  <li class="nav-item {{\Request::is('organization/profile*') ? 'active' :''}}">
                    <a class="nav-link" href="{{URL::to('organization/profile')}}">
                      <span class="sidebar-mini"> EP </span>
                      <span class="sidebar-normal"> Edit Profile </span>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
          <ul class="nav">
            <li class="nav-item  {{\Request::is('/') ? 'active':''}} ">
              <a class="nav-link" href="{{URL::to('/')}}">
                <i class="material-icons">dashboard</i>
                <p> Dashboard </p>
              </a>
            </li>
            <li class="nav-item {{\Request::is('projects*') ? 'active':''}}">
              <a class="nav-link" href="{{route('projects.index')}}">
                <i class="material-icons">assignment</i>
                <p> Projects </p>
              </a>
            </li>
            <li class="nav-item {{\Request::is('partners*') ? 'active':''}}">
              <a class="nav-link" href="{{route('partners.index')}}">
                <i class="material-icons">people_outline</i>
                <p> Partners </p>
              </a>
            </li>
            <li class="nav-item {{\Request::is('donors*') ? 'active':''}}">
              <a class="nav-link" href="{{route('donors.index')}}">
                <i class="material-icons">monetization_on</i>
                <p> Donors </p>
              </a>
            </li>
            <li class="nav-item ">
              <a class="nav-link" data-toggle="collapse" href="#pagesExamples">
                <i class="material-icons">settings</i>
                <p> System Settings
                  <b class="caret"></b>
                </p>
              </a>
              <div class="collapse {{\Request::is('budget-categories*') || \Request::is('mne-categories*') || \Request::is('ethnicities*') ? 'show' :''}}" id="pagesExamples">
                <ul class="nav">
                  <li class="nav-item {{\Request::is('budget-categories*') ? 'active' :''}} ">
                    <a class="nav-link " href="{{route('budget-categories.index')}}">
                      <span class="sidebar-mini"> BC </span>
                      <span class="sidebar-normal"> Budget Categories </span>
                    </a>
                  </li>
                  <li class="nav-item {{\Request::is('mne-categories*') ? 'active' :''}} ">
                    <a class="nav-link" href="{{route('mne-categories.index')}}">
                      <span class="sidebar-mini"> MNE </span>
                      <span class="sidebar-normal"> MNE Categories </span>
                    </a>
                  </li>
                  <li class="nav-item {{\Request::is('ethnicities*') ? 'active' :''}}  ">
                    <a class="nav-link" href="{{route('ethnicities.index')}}">
                      <span class="sidebar-mini"> E </span>
                      <span class="sidebar-normal"> Ethnicities </span>
                    </a>
                  </li>
                </ul>
              </div>
            </li>
          </ul>
        </div>
      </div>
      <div class="main-panel">
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
          <div class="container-fluid">
            <div class="navbar-wrapper">
              <div class="navbar-minimize">
                <button id="minimizeSidebar" class="btn btn-just-icon btn-white btn-fab btn-round">
                  <i class="material-icons text_align-center visible-on-sidebar-regular">more_vert</i>
                  <i class="material-icons design_bullet-list-67 visible-on-sidebar-mini">view_list</i>
                </button>
              </div>
              <a class="navbar-brand" href="#pablo">Dashboard</a>
            </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
              <span class="sr-only">Toggle navigation</span>
              <span class="navbar-toggler-icon icon-bar"></span>
              <span class="navbar-toggler-icon icon-bar"></span>
              <span class="navbar-toggler-icon icon-bar"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end">
              <form class="navbar-form">
                <div class="input-group no-border">
                  <input type="text" value="" class="form-control" placeholder="Search...">
                  <button type="submit" class="btn btn-white btn-round btn-just-icon">
                    <i class="material-icons">search</i>
                    <div class="ripple-container"></div>
                  </button>
                </div>
              </form>
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" href="#pablo">
                    <i class="material-icons">dashboard</i>
                    <p class="d-lg-none d-md-block">
                      Stats
                    </p>
                  </a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="material-icons">notifications</i>
                    <span class="notification">5</span>
                    <p class="d-lg-none d-md-block">
                      Some Actions
                    </p>
                  </a>
                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="#">Mike John responded to your email</a>
                    <a class="dropdown-item" href="#">You have 5 new tasks</a>
                    <a class="dropdown-item" href="#">You're now friend with Andrew</a>
                    <a class="dropdown-item" href="#">Another Notification</a>
                    <a class="dropdown-item" href="#">Another One</a>
                  </div>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link" href="#pablo" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="material-icons">person</i>
                    <p class="d-lg-none d-md-block">
                      Account
                    </p>
                  </a>
                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                    <a class="dropdown-item" href="#">Profile</a>
                    <a class="dropdown-item" href="#">Settings</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Log out</a>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <!-- End Navbar -->
        <div class="content">
          <div class="content">
            <div class="container-fluid">